import { defaultPolicy, type Actor, type Budget, type Case, type Data, type Role, type Route } from './model.ts';
import { newCase } from './workflow.ts';

export const demoCustomers = [{ id: 'DEMO-H001', name: '演练医院一（非真实客户）', region: '演练大区' }, { id: 'DEMO-H002', name: '演练医院二（非真实客户）', region: '演练大区' }];
export const demoBudgets: Budget[] = [{ id: 'DEMO-BUDGET-2026', customerId: 'DEMO-H001', hospital: demoCustomers[0].name, period: '2026', region: '演练大区', totalCents: 10_000_000, usedCents: 0, lockedCents: 0, revision: 1, evidence: '演练额度，非真实批准' }];
export function demoActor(role: Role): Actor { return { id: 'demo-applicant', email: `${role}@example.test`, name: `演练 · ${role}`, roles: [role], regions: ['*'], team: 'demo', demo: true }; }
export function demoData(route: Route = 'A'): Data {
  const future = new Date(); future.setDate(future.getDate() + 180); const end = future.toISOString().slice(0, 10);
  return {
    title: `${route}类流程演练（非真实项目）`, channel: '月度计划', targetMonth: new Date().toISOString().slice(0, 7), department: '学术支持部（演练）', region: '演练大区', customerId: 'DEMO-H001', hospital: demoCustomers[0].name, clinicalDepartment: '生殖中心（演练）', background: '验证需求、专业评估、审批、执行与结题是否可以贯通。', businessBasis: '演练合作场景，不代表真实销量或客户', sampleType: '去标识化研究数据（演练）', sampleQuantity: '30份', sampleSource: '演练数据', centerCount: '1', expectedOutput: '研究数据报告与客户汇报', expectedDate: end, sponsorEmail: 'sponsor@example.test', strategicGoal: '验证研究方法并形成产品决策依据（演练）', productGap: '演练非标服务缺口', priceIntent: '客户价格意向待正式商务批准（演练）', urgentReason: '临时需求演练', cannotWait: '客户期限早于下一批次（演练）', customerDeadline: end,
    route, evaluationRoles: '研发、分析、商务、质量', intakeNote: '演练资料已齐备', regionalDemand: '确认演练需求与价格意向', marketConclusion: '演练临时通路有共性需求', reportBoundary: '仅用于流程演练，不作临床报告', transitionUntil: end, exitOwner: 'product@example.test', feasibility: '可行', technicalPlan: '演练方案：数据清理、分析、复核与报告，约4周', deliveryMode: '内部研发', testCost: '10000', testCostBasis: '10份×1000元（虚拟成本）', resourceSource: '演练研发经费', humanSamples: '否', externalContract: '否', customerPaid: route === 'C' ? '是' : '否', customerResources: '否', majorCommitment: '否', highRisk: '否', analysisCost: '2000', analysisBasis: '2人天×1000元（虚拟成本）', paperCost: '0', patentCost: '0', outsourcingCost: '0', otherCost: '0', serviceBasis: '无额外服务范围；零成本仅作演练', riskNote: '仅演练，不涉及真实业务风险批准', budgetId: 'DEMO-BUDGET-2026', budgetNote: '演练预算台账已核对', regionalOpinion: '同意在演练额度内投入并跟踪客户价值', marketingOpinion: '演练批准，按节点交付', approvalUntil: end, sponsorOpinion: '演练战略与资源确认，阶段决策必须由Sponsor确认', departmentOpinion: '演练部门资源承诺', centerResourceOpinion: '演练中心资源已确认', externalOpinion: '演练重大承诺会签', commercialOpinion: '演练价格、合同与回款条件', complianceOpinion: '仅演练流程，无真实临床准入结论', exceptionOpinion: '演练例外批准，不代表授权', exceptionUntil: end, fundingEvidence: '演练预算批准记录', scope: '仅完成演练范围，不包含临床诊断', sampleCommitment: '1个演练中心 / 30份模拟记录', executionDepartment: '演练执行部门', fundingSource: route === 'A' ? 'DEMO-BUDGET-2026' : '演练专项经费', deliverables: '研究报告一份，字段完整、可复核', deadline: end, managerEmail: 'pmo@example.test', acceptorEmail: 'pmo@example.test', planEvidence: '/演练资料/方案.pdf', resourceEvidence: '/演练资料/资源确认.pdf', quoteEvidence: 'DEMO-QUOTE', contractEvidence: 'DEMO-CONTRACT', paymentEvidence: '/演练资料/支付条件.pdf', ethicsEvidence: '/演练资料/伦理适用确认.pdf', complianceEvidence: '/演练资料/合规确认.pdf', outsourcingEvidence: '/演练资料/合作协议.pdf', acceptanceEvidence: '/演练资料/最终验收.pdf', outcomes: '完成演练报告，无真实论文或收入', followUp: 'IT核对流程角色和接口后再正式使用', actualCost: '11000', revenue: route === 'C' ? '15000' : '0', paymentStatus: route === 'C' ? '演练回款已确认' : '无客户收费', archiveEvidence: '/演练资料/结题包/',
  };
}
export function initialDemoCases(): Case[] { return (['A', 'B', 'C'] as Route[]).map(route => newCase(`demo-${route}`, `DEMO-REQ-${route}`, demoActor('applicant'), Date.now(), demoData(route), route)); }
export const demoPolicy = { ...defaultPolicy, authorizationCents: 5_000_000 };
